# Generated by Django 5.0.3 on 2024-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=10),
        ),
    ]
