# Generated by Django 5.0.3 on 2024-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs_app', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('U', 'Universal'), ('R', 'Restricted'), ('PG', 'Parental Guidence')], max_length=50),
        ),
    ]
